//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrintAssembler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BluePrintAssembler.Resources.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting raw data….
        /// </summary>
        internal static string ConvertingData {
            get {
                return ResourceManager.GetString("ConvertingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining enabled mods….
        /// </summary>
        internal static string DeterminngEnabledMods {
            get {
                return ResourceManager.GetString("DeterminngEnabledMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering game/mods location….
        /// </summary>
        internal static string DiscoveringLocations {
            get {
                return ResourceManager.GetString("DiscoveringLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {1} from {0}….
        /// </summary>
        internal static string ExecutingLuaFromMod {
            get {
                return ResourceManager.GetString("ExecutingLuaFromMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guessing load order….
        /// </summary>
        internal static string GuessingLoadOrder {
            get {
                return ResourceManager.GetString("GuessingLoadOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        internal static string LoadCompleted {
            get {
                return ResourceManager.GetString("LoadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from cache….
        /// </summary>
        internal static string LoadingFromCache {
            get {
                return ResourceManager.GetString("LoadingFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading mods….
        /// </summary>
        internal static string LoadingFromData {
            get {
                return ResourceManager.GetString("LoadingFromData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating enabled mods….
        /// </summary>
        internal static string LocatingEnabledMods {
            get {
                return ResourceManager.GetString("LocatingEnabledMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading mod settings….
        /// </summary>
        internal static string ReadingModSettings {
            get {
                return ResourceManager.GetString("ReadingModSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing temporary files….
        /// </summary>
        internal static string RemovingTempFiles {
            get {
                return ResourceManager.GetString("RemovingTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking mod {0}….
        /// </summary>
        internal static string UnpackingMod {
            get {
                return ResourceManager.GetString("UnpackingMod", resourceCulture);
            }
        }
    }
}
